export default {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  SET_TODOS: 'SET_TODOS',
  LOG_IN: 'LOG_IN',
  SIGN_UP: 'SIGN_UP',
  COMPLETE: 'COMPLETE',
  EDIT: 'EDIT',
  EDIT_STATE_CHANGE: 'EDIT_STATE_CHANGE',
  ERROR: 'ERROR',
  RESET_ERROR: 'RESET_ERROR',
  LOG_OUT: 'LOG_OUT'
}